config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'insigths#index'
  post '/recommends/:id', to: 'insigths#recommends', as: :recommends

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def user_traits
    personality.reject { |k, v| v.to_f < 0.5 }
  end

  def genres
    trait = user_traits.keys.sample

    case trait
    when 'Openness'
      'clasical'
    when 'Extraversion'
      'rap'
    when 'Agreeableness'
      'jazz'
    when 'Emotional range'
      'country'
    when 'Conscientiousness'
      'pop'
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/insigths_controller.rb
class InsigthsController < ApplicationController
  protect_from_forgery except: :recommends
  helper_method :users
  respond_to :html, :js

  def recommends
    user = User.find(params[:id])
    @personality = V1::PersonalityInsigth.call(user.username)
    unless user.personality.present?
      user.personality = user_personality
      user.save
    end

    @recommends = V1::RecommendMusic.call(user.genres)
    render 'recommends.js'
  end

  def user_personality
    {}.tap do |personality|
      @personality['personality'].each do |trait, value|
        personality[trait['name']] = trait['percentile']
      end
    end
  end

  private
    def users
      @users ||= User.order(created_at: :asc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insigths_helper.rb
module InsigthsHelper
end

app/views/insigths/_recommends.html.erb
<div class="row">
  <div class="col-md-4">
    <div class= "card" style="width: 18rem;">
      <div class="card-body">
        <h3 class="card-title">Personality</h5>
        <% personality['personality'].each do |trait| %>
          <%#= trait.inspect%>
          <p class="card-text">
            <strong>Trait Name:</strong> <%= trait['name'] %>
          </p>
          <p class="card-text">
            <strong>Percentile:</strong> <%= number_to_percentage(trait['percentile'], precision: 2) %>
          </p>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
  <div class= "col-md-8">
    <div class= "card">
      <% @recommends['albums']['album'].each do |album| %>
        <img class="card-img-top img-album" src="<%= album['image'].second['#text'] %>" alt="<%= album['name'] %>">
        <div class="card-body">
          <h5 class="card-title"><%= album['name'] %></h5>
          <p class="card-text"><strong>Artist:</strong> <%= album['artist']['name'] %></p>
          <a href="<%= album['url'] %>" class="btn btn-primary">Go to Artist</a>
        </div>
        <hr/>
      <% end %>
    </div>
  </div>
</div>

app/views/insigths/index.html.erb
<div class="row">
  <div class="col-md-3" >
    </br>
    </br>
    </br>
    </br>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">User</th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
        <tr>
          <th scope="row"><%= user.id %></th>
          <td><%= link_to user.username, recommends_path(user), method: :post, remote: true %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-1"></div>
  <div class="col-md-8" >
    </br>
    </br>
    </br>
    </br>
    <h1>Music Recommends</h1>
    <div class="music_recommends"">Select a user to show information</div>
  </div>
</div>

app/views/insigths/recommends.js.erb
$('.music_recommends').empty().append("<%= escape_javascript(render(partial: 'recommends', locals: { personality: @personality, recommends: @recommends })) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Insigths", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Users</a></li>
          <li><a href="#about">Genres</a></li>
          <!--<li><a href="#contact">Contact</a></li>-->
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>